name: actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    name: actionlint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: actionlint
        uses: reviewdog/action-actionlint@v1.15.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
