name: CI

on:
  pull_request:
  push:
    branches:
      - wdb

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1.3.0

      - name: Clippy
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: cargo test --no-run --locked

      - name: Test
        run: cargo test -- --nocapture --quiet
